apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-pv
spec:
  storageClassName: disk-pv-class
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
